package edu.uga.cs.countryquiz;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;

public class ResultsData {

    private static final String DEBUG_TAG = "ResultsData";

    private SQLiteDatabase db;

    private static SQLiteOpenHelper resultsDBHelper;

    private static final String[] allColumns = {
            ResultsDBHelper.COLUMN_ID,
            ResultsDBHelper.COLUMN_DATE,
            ResultsDBHelper.COLUMN_GRADE,
    };

    public ResultsData ( Context context ) {
        this.resultsDBHelper = ResultsDBHelper.getInstance( context );
    }

    // Open the database
    public void open() {
        db = resultsDBHelper.getWritableDatabase();
        Log.d( DEBUG_TAG, "JobLeadsData: db open" );
    }

    // Close the database
    public void close() {
        if( resultsDBHelper != null ) {
            resultsDBHelper.close();
            Log.d(DEBUG_TAG, "JobLeadsData: db closed");
        }
    }

    public boolean isDBOpen()
    {
        return db.isOpen();
    }

    // Retrieve all results and return them as a List.
    // This is how we restore persistent objects stored as rows in the country table in the database.
    // For each retrieved row, we create a new Country (Java POJO object) instance and add it to the list.
    public List<Results> retrieveAllResults() {

        // create the new country arraylist
        ArrayList<Results> results_list = new ArrayList<>();
        Cursor cursor = null;
        int columnIndex;

        try {
            // Execute the select query and get the Cursor to iterate over the retrieved rows
            cursor = db.query( ResultsDBHelper.TABLE_RESULTS, allColumns,
                    null, null, null, null, null );


            Log.d(DEBUG_TAG, ""+ cursor.getCount());

            // collect all job leads into a List
            if( cursor != null && cursor.getCount() > 0 ) {

                while( cursor.moveToNext() ) {

                    if( cursor.getColumnCount() >= 2) {

                        // get all attribute values of this job lead
                        columnIndex = cursor.getColumnIndex( ResultsDBHelper.COLUMN_ID );
                        int id = cursor.getInt( columnIndex );
                        columnIndex = cursor.getColumnIndex( ResultsDBHelper.COLUMN_DATE);
                        String date = cursor.getString( columnIndex );
                        columnIndex = cursor.getColumnIndex( ResultsDBHelper.COLUMN_GRADE);
                        int grade = cursor.getInt( columnIndex );

                        // create a new JobLead object and set its state to the retrieved values
                        Results results = new Results( date, grade );
                        results.setId(id); // set the id (the primary key) of this object
                        // add it to the list
                        results_list.add( results );
                        Log.d(DEBUG_TAG, "Retrieved results: " + results);
                    }
                }
            }


            if( cursor != null )
                Log.d( DEBUG_TAG, "Number of records from DB: " + cursor.getCount() );
            else
                Log.d( DEBUG_TAG, "Number of records from DB: 0" );
        }
        catch( Exception e ){
            Log.d( DEBUG_TAG, "Exception caught: " + e );
        }
        finally{
            // we should close the cursor
            if (cursor != null) {
                cursor.close();
            }
        }
        // return a list of retrieved job leads
        return results_list;
    }

    // Store a new job lead in the database.
    public Results storeResult( Results result ) {

        // Prepare the values for all of the necessary columns in the table
        // and set their values to the variables of the JobLead argument.
        // This is how we are providing persistence to a JobLead (Java object) instance
        // by storing it as a new row in the database table representing job leads.
        ContentValues values = new ContentValues();
//        values.put( ResultsDBHelper.COLUMN_ID, result.getID());
        values.put( ResultsDBHelper.COLUMN_DATE, result.getDate() );
        values.put( ResultsDBHelper.COLUMN_GRADE, result.getGrade() );

        // Insert the new row into the database table;
        // The id (primary key) is automatically generated by the database system
        // and returned as from the insert method call.
        long id = db.insert( ResultsDBHelper.TABLE_RESULTS, null, values );

        // store the id (the primary key) in the JobLead instance, as it is now persistent
        result.setId( (int) id );

        Log.d( DEBUG_TAG, "Stored new job lead with id: " + String.valueOf( result.getID() ) );
        Log.d( DEBUG_TAG, "Stored new job lead with id: " + String.valueOf( result.getDate() ) );
        Log.d( DEBUG_TAG, "Stored new job lead with id: " + String.valueOf( result.getGrade() ) );

        return result;
    }

}
